--[[
README:

Change SUB resolution to match video PATCH

Feature:
After you changing SUB resolution to match video, 
The BORD and SHADOW become weird,
This is the patch script to fix it!

The default ratio is 3.75,
and if you want to fix the 720p SUB into the video for example,
Just set the argument to 1.5.

Manual:
1. Duplicate the following settings to the original ass script
    [Script Info]
    ; Script generated by Aegisub 3.2.2
    ; http://www.aegisub.org/
    Title: Default Aegisub file
    ScriptType: v4.00+
    WrapStyle: 0
    ScaledBorderAndShadow: no
    YCbCr Matrix: TV.709
    PlayResX: 384
    PlayResY: 288
2. Open the ass script with Aegisub and then open the video
3. Check "change subtitles resolution to match video" and press OK
4. Select ALL THE LINES and run this LUA script

Bug Report:

Updated on 18th, Jan 2021
]]

--Script properties
script_name="C Change SUB resolution to match video PATCH"
script_description="Change SUB resolution to match video PATCH"
script_author="chaaaaang"
script_version="1.0"

--GUI
dialog_config={
    {class="label",label="ratio",x=0,y=0,width=2},
    {class="floatedit",name="ratio",value=3.75,x=0,y=1,width=2},
    {class="label",x=0,y=2,width=2,height=2,label="384x288 -> 1920x1080 arg:3.75\n1280x720 -> 1920x1080 arg:1.5"}
}
buttons={"Run","Quit"}

function main(subtitle, selected)
    
    pressed, result = aegisub.dialog.display(dialog_config,buttons)
    if (pressed=="Quit") then aegisub.cancel() end

	for si,li in ipairs(selected) do
		
		local line=subtitle[li]
		
        local ltext = line.text

        ltext = ltext:gsub("(\\bord)([%d%.]+)",function(a,b) return a..b/result["ratio"] end)

        ltext = ltext:gsub("(\\[xy]?shad)([%d%.%-]+)",function(c,d) return c..d/result["ratio"] end)

        line.text = ltext

		subtitle[li]=line
		
	end
	
	aegisub.set_undo_point(script_name)
	return selected
end

--Register macro (no validation function required)
aegisub.register_macro(script_name,script_description,main)
